export const FETCH_ALL_SEATS = 'FETCH_ALL_SEATS';
export const SELECT_SEAT = 'SELECT_SEAT';
export const CLEAR_SELECTION_SEATS = 'CLEAR_SELECTION_SEATS';

export const FILTER_ALL_SEATS = 'FILTER_ALL_SEATS';
export const FILTER_RESERVED_SEATS = 'FILTER_RESERVED_SEATS';
export const FILTER_SELECTED_SEATS = 'FILTER_SELECTED_SEATS';
